; PlatformIO - Percobaan 1: ESP32 UART Bridge
; Full Duplex transparent bridge: USB Serial <-> UART2 (STM32)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
