; PlatformIO - Percobaan 2: ESP32 Half Duplex Bridge
; Single wire half-duplex bridge: USB Serial <-> HardwareSerial2 (STM32)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
